<!-- simulator/index -->
<?php if (isset($this->messages) && count($this->smessages) > 0): ?>
<?php foreach ($this->messages as $message): ?>
<div class="row alert-box error">
    <?php echo $message ?>
    <a href="" class="close">&times;</a>
</div>
<?php endforeach; ?>
<?php endif; ?>

<form method="post" id="form" action="<?php echo $this->url(array('action' => 'index')) ?>" class="custom nice">
    <div class="row">
        <div class="four columns">
            <h4>Basic</h4><hr />
            <label for="vendor">Vendor
                <select name="vendor" id="vendor" class="expand">
                    <option<?php echo (isset($this->params['vendor']) && $this->params['vendor'] == 'BML') ? ' selected' : null ?>>BML</option>
                    <option<?php echo (isset($this->params['vendor']) && $this->params['vendor'] == 'Xeon') ? ' selected' : null ?>>Xeon</option>
                </select>
            </label>

            <label for="vendor">Method
                <select name="method" id="method" class="expand">
                    <option<?php echo (isset($this->params['method']) && $this->params['method'] == 'Redirect') ? ' selected' : null ?>>Redirect</option>
                    <option<?php echo (isset($this->params['method']) && $this->params['method'] == 'Direct') ? ' selected' : null ?>>Direct</option>
                </select>
            </label>

            <label for="password" id="fldPassword">Transaction Password
                <input type="text" name="password" id="password" value="<?php echo isset($this->params['password']) ? $this->params['password'] : null ?>" class="input-text expand" />
                <?php echo isset($this->errors['password']) ? $this->partial('index/error.phtml', array('message' => $this->errors['password'])) : null ?>
            </label>

            <label for="merchantId">Merchant Id
                <input type="text" name="merchantId" id="merchantId" value="<?php echo isset($this->params['merchantId']) ? $this->params['merchantId'] : null ?>" class="input-text expand" />
                <?php echo isset($this->errors['merchantId']) ? $this->partial('index/error.phtml', array('message' => $this->errors['merchantId'])) : null ?>
            </label>

            <label for="amount">Amount
                <input type="text" name="amount" id="amount" value="<?php echo isset($this->params['amount']) ? $this->params['amount'] : null ?>" class="input-text expand" />
                <?php echo isset($this->errors['amount']) ? $this->partial('index/error.phtml', array('message' => $this->errors['amount'])) : null ?>
            </label>

            <label for="currency">Currency
                <select name="currency" id="currency" class="expand">
                    <option selected>MVR</option>
                    <option>USD</option>
                </select>
            </label>

            <label for="orderId">Order Id
                <input type="text" name="orderId" id="orderId" value="<?php echo isset($this->params['orderId']) ? $this->params['orderId'] : null ?>" class="input-text expand" />
                <?php echo isset($this->errors['orderId']) ? $this->partial('index/error.phtml', array('message' => $this->errors['orderId'])) : null ?>
            </label>
        </div>

        <div id="options" class="four columns end">
            <div id="xeonOptions" style="margin-bottom: 10px;">
                <h4>Xeon Simulator Options</h4><hr />

                <hr />
            </div>

            <div id="directOptions">
                <h4>Direct Method Options</h4><hr />
                <label for="cardNumber">Card Number
                    <input type="text" name="cardNumber" id="cardNumber" value="<?php echo isset($this->params['cardNumber']) ? $this->params['cardNumber'] : null ?>" maxlength="19" class="input-text expand" />
                    <?php echo isset($this->errors['cardNumber']) ? $this->partial('index/error.phtml', array('message' => $this->errors['cardNumber'])) : null ?>
                </label>

                <label for="cardExpiry">Card Expiry (MMYY)
                    <input type="text" name="cardExpiry" id="cardExpiry" maxlength="4" value="<?php echo isset($this->params['cardExpiry']) ? $this->params['cardExpiry'] : null ?>" class="input-text expand" />
                    <?php echo isset($this->errors['cardExpiry']) ? $this->partial('index/error.phtml', array('message' => $this->errors['cardExpiry'])) : null ?>
                </label>

                <label for="cardCvv2">Card CVV2
                    <input type="text" name="cardCvv2" id="cardCvv2" maxlength="4" value="<?php echo isset($this->params['cardCvv2']) ? $this->params['cardCvv2'] : null ?>" class="input-text expand" />
                    <?php echo isset($this->errors['cardCvv2']) ? $this->partial('index/error.phtml', array('message' => $this->errors['cardCvv2'])) : null ?>
                </label>
            </div>
        </div>

        <div class="four columns end">
            <h4>Some Instructions</h4><hr />
            <div>
                <p>Some instructions on the basic options and using the web
                interface to validate transaction input.</p>

                <p>Some instructions on the basic options and using the web
                interface to validate transaction input.</p>

                <p>Some instructions on the basic options and using the web
                interface to validate transaction input.</p>
            </div>
            <hr />
            <input type="submit" name="action" value="Process" class="button nice" />
        </div>
    </div>
</form>

<script type="text/javascript">
$(function() {
    function getFormFields() {
        return {
            vendor: $('#vendor')[0],
            password: $('#password')[0],
            merId: $('#merId')[0],
            purchaseAmount: $('#purchaseAmount')[0],
            purchaseCurrency: $('#purchaseCurrency')[0],
            orderId: $('#orderId')[0],
            signature: $('#signature')[0]
        };
    }

    function getFormValues() {
        var fields = getFormFields();
        var values = {};
        $.each(fields, function(index, item) {
            values[index] = item.value;
        });
        return values;
    }

    function toggleXeonOptions(display) {
        if (display == 'show') {
            $('#xeonOptions').slideDown('fast', toggleOptions);
        } else {
            $('#xeonOptions').slideUp('fast', toggleOptions);
        }

        if ($('#xeonOptions').css('display') == 'none'
            && $('#directOptions').css('display') == 'none') {
            $('#options').hide('fast');
        } else {
            $('#options').show('fast');
        }
    }

    function toggleDirectOptions(display) {
        if (display === 'show') {
            $('#directOptions').slideDown('fast', toggleOptions);
        } else {
            $('#directOptions').slideUp('fast', toggleOptions);
        }

        if ($('#directOptions').css('display') == 'none'
            && $('#xeonOptions').css('display') == 'none') {
            $('#options').hide('fast');
        } else {
            $('#options').show('fast');
        }
    }

    function toggleOptions() {
        if ($('#xeonOptions').css('display') == 'none' &&
            $('#directOptions').css('display') == 'none') {
            $('#options').hide('fast');
        } else {
            $('#options').show('fast');
        }
    }

    $('#vendor').on('change', function(e) {
        var xeonOptions = $('#xeonOptions');
        if (e.target.value === 'Xeon') {
            $('#fldPassword').hide('fast');
            toggleXeonOptions('show');
        } else {
            $('#fldPassword').show('fast');
            toggleXeonOptions('hide');
        }
    });

    /* Change listener for method field. */
    $('#method').on('change', function(e) {
        var directOptions = $('#directOptions');
        if (e.target.value == 'Redirect') {
            toggleDirectOptions('hide');
        } else if (e.target.value == 'Direct') {
            toggleDirectOptions('show');
        }
    });

    /* Initialize display of xeon options. */
    if ($('#vendor')[0].value == 'BML') {
        $('#xeonOptions').hide();
    } else {
        $('#xeonOptions').show();
    }

    /* Initialize display of direct method options column. */
    if ($('#method')[0].value == 'Redirect') {
        $('#directOptions').hide();
    } else {
        $('#directOptions').show();
    }

    if ($('#xeonOptions').css('display') == 'none' &&
        $('#directOptions').css('display') == 'none') {
        $('#options').hide();
    } else {
        $('#options').show();
    }
});
</script>
