<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width" />

    <title>Xeon Simulator</title>

    <!-- Included CSS Files -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl ?>/foundation/stylesheets/foundation.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl ?>/styles.css">

    <!--[if lt IE 9]>
        <link rel="stylesheet" href="stylesheets/ie.css">
    <![endif]-->

    <script src="<?php echo $this->baseUrl ?>/foundation/javascripts/modernizr.foundation.js"></script>
    <script src="<?php echo $this->baseUrl ?>/foundation/javascripts/jquery.min.js"></script>

    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    <!-- container -->
    <div class="container">
        <div class="row">
            <h3><a href="<?php echo $this->baseUrl ?>/simulator">Xeon Simulator</a></h3>
            <hr />
        </div>
        <?php echo $this->layout()->content ?>

        <div class="row">
            <hr />
            Copyright &copy; Aedea - 2012
        </div>
    </div>
    <!-- container -->

    <!-- Included JS Files -->
    <script src="<?php echo $this->baseUrl ?>/foundation/javascripts/foundation.js"></script>
    <script src="<?php echo $this->baseUrl ?>/foundation/javascripts/app.js"></script>
</body>
</html>
